### ISSUE TITLE
S7 support

### ISSUE THREAD

**Issue by Mattrees007** [amosyuen/ha-tplink-deco#132] opened 2022-12-29 09:32 UTC
Hi I have recently added 2off S7 units to my mesh (m4R) and have made an S7 the main unit.

In order to add S7 support to your integration I assume you need some samples of traffic,etc?

Please advise what you need.I'm happy to provide.

**Comment by amosyuen** [comment] 2022-12-29 19:34
Duplicate of https://github.com/amosyuen/ha-tplink-deco/issues/130

**Closed by amosyuen** 2022-12-29 19:34 UTC
