### ISSUE TITLE
Integration requries reconfiguration: Authentication failed while fetching tplink_deco-clients data: Data empty

### ISSUE THREAD

**Issue by Emrill** [amosyuen/ha-tplink-deco#142] opened 2023-01-25 16:26 UTC
### Problem

Yesterday the integration has started saying "Integration requires reconfiguration" I goto the integration and press reconfigure, the fields are already completed (and haven't changed) I press submit and get a successful message but then the error starts again 

### TP-Link Deco Version

Current 

### Router Model

Deco m5

### Debugging Information

None

**Comment by amosyuen** [comment] 2023-01-25 18:56
Please read through the instructions in the reconfiguration prompt.

**Comment by bachoo786** [comment] 2023-01-31 12:00
same issue here :(

**Comment by bachoo786** [comment] 2023-01-31 12:14
@amosyuen so in the instructions in the reconfiguration prompt dont mention anything really, it takes you to the standard login credentials etc under the readme file which I have followed well i.e. username is admin and I have made another manager account that I am using on my mobile. 

Also I am using the latest version of this integration but still no joy. Can you help please?

**Comment by amosyuen** [comment] 2023-01-31 18:29
Maybe I need to make it more explicit. From https://github.com/amosyuen/ha-tplink-deco#login-credentials:

> Also whenever the owner logs in, all other sessions for the owner will be logged out. So if you log in with the owner credentials in the mobile app, it will cause the integration to be logged out, sometimes resulting in 403 errors

Could you confirm whether you are logging in with owner credentials elsewhere?

**Comment by bachoo786** [comment] 2023-01-31 19:04
> Maybe I need to make it more explicit. From https://github.com/amosyuen/ha-tplink-deco#login-credentials:
> 
> > Also whenever the owner logs in, all other sessions for the owner will be logged out. So if you log in with the owner credentials in the mobile app, it will cause the integration to be logged out, sometimes resulting in 403 errors
> 
> Could you confirm whether you are logging in with owner credentials elsewhere?

No need to make it more explicit mate its all understandable. However I have followed your instructions when I first started using your integration I.e.

"Recommend that you create a separate manager account with full permissions to manage the router manually in the mobile app and use the owner credentials only for this integration. If you need to use the owner account to do some manual management, recommend disabling this integration temporarily."

Does that make sense?!

**Comment by amosyuen** [comment] 2023-01-31 19:41
Ok thanks for confirming, then please turn on debugging and paste logs from when integration config fails. https://github.com/amosyuen/ha-tplink-deco/blob/master/DEBUGGING.md#general-steps

**Comment by antonyslater** [comment] 2023-02-01 10:09
I too have the same issue, I have rolled back to v3.0.0 which following a single reconfiguration message has remained stable since.  I also tried (never needed before v3.1.0) creating a separate logging for my phone Deco app, this made no difference on 3.1.0, the integration seems to "work" for a time but then stops with the same reconfiguration message over and over.

**Comment by Gferretta** [comment] 2023-02-01 12:53
> @amosyuen so in the instructions in the reconfiguration prompt dont mention anything really, it takes you to the standard login credentials etc under the readme file which I have followed well i.e. username is admin and I have made another manager account that I am using on my mobile. 
> 
> Also I am using the latest version of this integration but still no joy. Can you help please?

Hi
Can you explain me how/where you create a New manager account for use in a mobile DECO app?
Thanks

PS: sorry for OT

**Comment by antonyslater** [comment] 2023-02-01 13:10
> > @amosyuen so in the instructions in the reconfiguration prompt dont mention anything really, it takes you to the standard login credentials etc under the readme file which I have followed well i.e. username is admin and I have made another manager account that I am using on my mobile.
> > Also I am using the latest version of this integration but still no joy. Can you help please?
> 
> Hi Can you explain me how/where you create a New manager account for use in a mobile DECO app? Thanks
> 
> PS: sorry for OT

You need to:
1) Head to TP-Link online and create a new account (with a different email address)
2) In the app you add that account as a manager using the "new" email address
3) You need to log out of the app from your original account
4) Re-login using the new account you've just created.

Hope this helps. :-)

**Comment by Gferretta** [comment] 2023-02-01 18:07
> > > @amosyuen so in the instructions in the reconfiguration prompt dont mention anything really, it takes you to the standard login credentials etc under the readme file which I have followed well i.e. username is admin and I have made another manager account that I am using on my mobile.
> > > Also I am using the latest version of this integration but still no joy. Can you help please?
> > 
> > Hi Can you explain me how/where you create a New manager account for use in a mobile DECO app? Thanks
> > 
> > PS: sorry for OT
> 
> You need to:
> 1) Head to TP-Link online and create a new account (with a different email address)
> 2) In the app you add that account as a manager using the "new" email address
> 3) You need to log out of the app from your original account
> 4) Re-login using the new account you've just created.
> 
> Hope this helps. :-)

Thanks
I'm going to try it

Regards

**Comment by myshyak** [comment] 2023-02-01 21:46
Have also the same problem.
Trying to get you logs as per manual, but getting this error:
The system cannot restart because the configuration is not valid: Integration error: logs - Integration 'logs' not found.
Please advice how to handle this

**Comment by myshyak** [comment] 2023-02-01 22:04
Ok, got following error:
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:91
Integration: TP-Link Deco
First occurred: 1 февраля 2023 г., 23:57:43 (3 occurrences)
Last logged: 00:00:49

Error testing credentials:

However, easily login to web admin panel using password I enter into integration and the IP address of server

**Comment by antonyslater** [comment] 2023-02-02 08:18
OK, so even with a separate account and having rolled back to v3.0.0 I am still getting this error message that I've never had before...  This starts when my deco's reboot at 02:30 in the morning so I know there is no one else logging in to the admin account at that time.  I wonder if there is a limit on the number of retries maybe or the duration retries occur?  I'm kinda clutching at straws here though now as every morning I have to reconfigure the integration just to be able to track devices.

Logger: custom_components.tplink_deco
Source: helpers/update_coordinator.py:168
Integration: TP-Link Deco ([documentation](https://github.com/amosyuen/ha-tplink-deco), [issues](https://github.com/amosyuen/ha-tplink-deco/issues))
First occurred: 02:30:47 (4 occurrences)
Last logged: 07:35:05

Error requesting tplink_deco-decos data: Cannot connect to host 192.168.1.30:80 ssl:default [Connect call failed ('192.168.1.30', 80)]
Error requesting tplink_deco-clients data: Cannot connect to host 192.168.1.30:80 ssl:default [Connect call failed ('192.168.1.30', 80)]
Authentication failed while fetching tplink_deco-clients data: Data empty. Likely caused by logging in with admin account on another device. See https://github.com/amosyuen/ha-tplink-deco#login-credentials.
Authentication failed while fetching tplink_deco-decos data: Data empty. Likely caused by logging in with admin account on another device. See https://github.com/amosyuen/ha-tplink-deco#login-credentials.

**Comment by amosyuen** [comment] 2023-02-02 08:59
Thanks for the logs @antonyslater, I added a retry for that empty response case in v3.1.1 see if that helps.

**Comment by antonyslater** [comment] 2023-02-03 08:34
> Thanks for the logs @antonyslater, I added a retry for that empty response case in v3.1.2 see if that helps.

Hi @amosyuen,

I have left v3.1.2 running since you posted it yesterday, and it did not need reconfiguring beyond the initial one just after I updated it.  However I log on this morning to find that it has failed once again in the night (02:30) when my deco's are force rebooted...  Not sure how things have changed but I never needed to do this daily before v3.1.0 and my deco's have been rebooting nightly for at least 9 months.

I will attach the log entries I have obtained this morning so as to not "spam" this thread...  Some from 02:30 and some from 08:26, hope these help.
[02-40-25 (3 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10577060/02-40-25.3.occurrences.txt)
[08-26-50 (9 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10577061/08-26-50.9.occurrences.txt)
[08-26-52 (4 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10577062/08-26-52.4.occurrences.txt)
[02-30-29 (2 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10577063/02-30-29.2.occurrences.txt)
[02-30-29 (18 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10577064/02-30-29.18.occurrences.txt)
[02-30-35 (54 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10577065/02-30-35.54.occurrences.txt)

**Comment by amosyuen** [comment] 2023-02-04 10:21
I added some code to clear auth if connection failed, which resolves the problem for me when I reboot the decos. Please try https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.1.4 and see if that helps.

**Comment by antonyslater** [comment] 2023-02-05 13:15
> I added some code to clear auth if connection failed, which resolves the problem for me when I reboot the decos. Please try https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.1.4 and see if that helps.

Updated and left over night to see what happens... seemed OK when I first loaded HA but after about 5 mins I got the usual reconfigure message...  These are my logs form this morning.

[02-31-02 (2 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10611099/02-31-02.2.occurrences.txt)
[02-31-35 (3 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10611100/02-31-35.3.occurrences.txt)
[02-31-38 (2 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10611101/02-31-38.2.occurrences.txt)
[02-31-38 (18 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10611102/02-31-38.18.occurrences.txt)
[02-32-05 (32 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10611103/02-32-05.32.occurrences.txt)

**Comment by myshyak** [comment] 2023-02-05 13:21
Fixed my issue. Appeared that the integration can't be configured via hass.io . Managed to make the configuration via local network.

**Comment by antonyslater** [comment] 2023-02-07 08:48
Todays logs, same reconfiguration required this morning... One has a different feel to it today though (32 occurrences)... I will stop sending these now unless you ask for them. :-)

[02-30-57 (1 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10673126/02-30-57.1.occurrences.txt)
[02-30-57 (2 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10673127/02-30-57.2.occurrences.txt)
[02-31-30 (2 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10673128/02-31-30.2.occurrences.txt)
[02-31-30 (18 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10673129/02-31-30.18.occurrences.txt)
[02-31-36 (32 occurrences).txt](https://github.com/amosyuen/ha-tplink-deco/files/10673130/02-31-36.32.occurrences.txt)

**Comment by amosyuen** [comment] 2023-02-08 09:46
@antonyslater 
* `Cannot connect to host` errors are expected when you are rebooting the deco and shouldn't really affect the integration.
* `Timeout` are errors from deco being slow. You can try tweaking timeout config params added in  https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.3.0
* `Future exception was never retrieved` is a legit error that should be fixed in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.3.0

**Comment by antonyslater** [comment] 2023-02-08 11:18
Cheers @amosyuen I have updated now, will see how things go overnight again and let you know.  Thanks again for your efforts, it really is much appreciated. :-)

**Comment by bachoo786** [comment] 2023-02-08 12:11
Is the latest version already pushed out on HACS?

**Comment by antonyslater** [comment] 2023-02-08 12:19
> Is the latest version already pushed out on HACS?

I had to restart for it to show as an update available in HACS, although I believe if you go into the integration in HACS you have the option to download the latest version even before it is "reported" as having an update available.

**Comment by bachoo786** [comment] 2023-02-08 12:22
> > Is the latest version already pushed out on HACS?
> 
> I had to restart for it to show as an update available in HACS, although I believe if you go into the integration in HACS you have the option to download the latest version even before it is "reported" as having an update available.

Nice one thank you

**Comment by antonyslater** [comment] 2023-02-09 11:26
> @antonyslater
> 
> * `Cannot connect to host` errors are expected when you are rebooting the deco and shouldn't really affect the integration.
> * `Timeout` are errors from deco being slow. You can try tweaking timeout config params added in  https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.3.0
> * `Future exception was never retrieved` is a legit bug that should be fixed in https://github.com/amosyuen/ha-tplink-deco/releases/tag/v3.3.0

Hi @amosyuen, great news, no configuration error message this morning....  I updated yesterday and set the new settings as follows:
Timeout error retry count: 10
Timeout seconds: 30 (default I believe)

THANK YOU again for all your help with this. :-)

**Comment by amosyuen** [comment] 2023-02-09 18:40
Glad that is seems resolved so far!

**Comment by amosyuen** [comment] 2023-04-23 06:08
Closing issue as resolved

**Closed by amosyuen** 2023-04-23 06:08 UTC
Labels: bug
