### ISSUE TITLE
async_add_job will be deprecated

### ISSUE THREAD

**Issue by hastaboera** [amosyuen/ha-tplink-deco#290] opened 2024-05-09 06:40 UTC
### Problem

Hi,

This is a future issue.
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'tplink_deco' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/tplink_deco/__init__.py, line 166: hass.async_add_job

Thanks in advance!

### TP-Link Deco Version

1.6.3

### Router Model

DECO M9 plus

### Debugging Information

WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'tplink_deco' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/tplink_deco/__init__.py, line 166: hass.async_add_job

**Comment by amosyuen** [comment] 2024-05-09 20:18
Duplicate of https://github.com/amosyuen/ha-tplink-deco/issues/278#issuecomment-2092909462

**Closed by amosyuen** 2024-05-09 20:18 UTC
