### ISSUE TITLE
Retrying setup: Cannot connect to host none:80 ssl:default [Name does not resolve]

### ISSUE THREAD

**Issue by antonyslater** [amosyuen/ha-tplink-deco#69] opened 2022-05-19 20:58 UTC
## Version of the custom_component
v2.1.1

## Deco Model
3 x M4(v2)
Main (Cabinet)
Second (Landing)
Third (Kitchen)

## Describe the bug
Initial setup went fine, configured and found all devices, needed to restart HACS and HA to update other integrations and found that the error below was present on the HA Integrations page.

Retrying setup: Cannot connect to host none:80 ssl:default [Name does not resolve]

When I checked the config, the main host had defaulted back to the original address 192.168.0.1 and the password had disappeared.  Have tried several times to reset configuration which it seems to do (says finished successfully) but the error remains and the config entries are still missing.

## Home Assistant log
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:390
Integration: TP-Link Deco ([documentation](https://github.com/amosyuen/ha-tplink-deco), [issues](https://github.com/amosyuen/ha-tplink-deco/issues))
First occurred: 21:41:46 (8 occurrences)
Last logged: 21:47:14

Fetch keys client error: Cannot connect to host none:80 ssl:default [Name does not resolve]

Log Details (WARNING)
Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 21:50:52 (1 occurrences)
Last logged: 21:50:52

Config entry 'WiFi Network' for tplink_deco integration not ready yet: Cannot connect to host none:80 ssl:default [Name does not resolve]; Retrying in background

**Comment by antonyslater** [comment] 2022-05-20 07:11
I have tried this morning to remove and reinstall the integration in HA, it works to get to the same point as last night in that it works but as soon as I restart HA I get the error messages back again.

Any other tests I can do to help diagnose please do let me know.

**Comment by schwieb** [comment] 2022-05-27 17:00
Having exactly the same issue.

**Comment by amosyuen** [comment] 2022-06-04 22:08
@antonyslater That's quite the mystery to me, since it says "Cannot connect to host none:80 ssl:default", that indicates that the host config field value is not set, hence the "none". That is pretty strange since it worked before. So seems to indicate it's not saving the host value somehow? I'm unable to repro at all.

Did you try turning on debug logs and see if you get any other interesting logs? Also does downgrading to v2.1.0 as @schwieb mentioned help you?

**Comment by schwieb** [comment] 2022-06-05 13:47
I agree that it doesn't seem to be saving the information. Unfortunately you also cannot edit/re-add and save them.

I wanted to clean up some settings so I completely wiped them, uninstalled, upgraded and readded the integration. You may want to try the same to duplicate the bug.

Now that I'm running the version 2.1.0 successfully, I can try upgrading from here to see if the settings are kept allowing it to work fine. I will do that later today or tomorrow morning and report back.

**Comment by schwieb** [comment] 2022-06-06 12:38
Ok, I upgraded and the application worked for the first boot.  Unfortunately, it stopped working again after a reboot with the same error:

Retrying setup: Cannot connect to host none:80 ssl:default [Name does not resolve]

**Comment by SignalGroup** [comment] 2022-06-12 14:58
I have the X20 with the same issue.

**Comment by 1h8fulkat** [comment] 2022-08-09 20:26
Same issue here on the Deco w3600

**Comment by darkmatter24** [comment] 2022-08-15 20:17
Same here on the Deco M5. 
It seems to work until I make any kind of change to the config (such as disabling some entities or changing an entity display name), the all entities go unavailable and won't come back until I delete and reinstall the integration.

**Comment by amosyuen** [comment] 2022-08-15 20:24
For people who are experiencing this error. Please do the following:

1. Turn on debug logs and confirm if you are getting that error `Cannot connect to host none:80 ssl:default [Name does not resolve]` or if you are getting other errors.
2. Try downgrading to v2.1.0 and let me know if that fixes the problem.

**Comment by darkmatter24** [comment] 2022-08-16 08:41
I'm on v2.1.0 and get the following errors:
```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host none:80 ssl:default [Name does not resolve]
homeassistant.exceptions.ConfigEntryNotReady: Cannot connect to host none:80 ssl:default [Name does not resolve]
```

After this all devices go permanently unavailable.

I think I've got to the bottom of my issue:
These errors happen as soon as I rename the integration (using the Three dots->Rename option in the integration UI). 
Everything is fine until then, but within seconds of renaming I get the above errors.

Changing the integration name back to what it was (the IP of my router) and restarting Home Assistant doesn't fix the problem, the only thing that helps is deleting the integration and re-installing.

**Comment by darkmatter24** [comment] 2022-08-16 11:15
Upgraded to v2.2.0 and get the same behaviour.

As well as changing the name of the integration I also get the errors if I change the 'Enable newly added entities' option through the UI.
So it's looking like it happens as soon as I make any kind of config change to the integration after initial install. If I leave it alone after initially setting it up then it works fine.

**Comment by schwieb** [comment] 2022-08-16 11:32
I no longer seem to be having the issue but I upgraded straight from 2.1.0 to 2.1.2.  I have not yet updated to 2.2.0

**Comment by 1h8fulkat** [comment] 2022-08-23 18:17
I'm unable to reproduce on 2.2.0

**Comment by amosyuen** [comment] 2022-09-25 23:20
Closing this issue for now as fixed.

**Closed by amosyuen** 2022-09-25 23:20 UTC
Labels: bug, not_enough_data
