### ISSUE TITLE
Home assistant log errors: Detected integration that restore_state.RestoreStateData.async_get_instance is deprecated, and not intended to be called by custom components

### ISSUE THREAD

**Issue by michpas** [amosyuen/ha-tplink-deco#206] opened 2023-07-18 12:45 UTC
### Problem

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 14:21:27 (1 occurrences)
Last logged: 14:21:27

Detected integration that restore_state.RestoreStateData.async_get_instance is deprecated, and not intended to be called by custom components; Pleaserefactor your code to use RestoreEntity instead; restore_state.async_get(hass) can be used in the meantime. Please report issue to the custom integration author for tplink_deco using this method at custom_components/tplink_deco/__init__.py, line 121: last_states = (await RestoreStateData.async_get_instance(hass)).last_states

### TP-Link Deco Version

x

### Router Model

M3

### Debugging Information

see problem reported in log file by HA

**Comment by amosyuen** [comment] 2023-07-20 08:20
Duplicate of #187

**Closed** 2023-07-20 08:36 UTC
